### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by heri0nd3** [gnumdk/lollypop#38] opened 2015-03-04 00:01 UTC
Seems I tried the new music player, Lollypop, I want to have some feature requests as well:

## Option to use Lollypop as a default player

Would it be nice if I can set Lollypop as a default multimedia player? Because when I go to _System_ -> _Preferences_ -> _Preferred Applications_ in MATE desktop environment (which I currently using it), On _Multimedia_ tab, under _Multimedia Player_ it is impossible to set Lollypop as a default music player. I would love to have that when I double-clicked the music files within the file manager.

![screenshot](https://cloud.githubusercontent.com/assets/6704448/6475193/6a2addd8-c1bc-11e4-978e-446fa1a81893.png)

## Internet radio

Wouldn't be nice if Lollypop has Internet radio feature as well? I can listen to music when I using steam URL to listen to their radio stations.

## Lyric viewer

This could be a must-have feature, this would fetch lyrics from LyricWiki and from a local file while playing the current music.

## Support for more music formats

Instead of just MP3, OGG and M4A, would be more powerful if Lollypop supports more support for audio formats such as SPC (SNES music file), NSF (NES sound format, used from 8-bit video game music), PSF (Portable Sound Format, used from video game music), PSF2 (PlayStation 2 music format), WMA, GYM, APE, etc., just like from Quod Libet and Audacious, which are there supported.

Thanks in advance!

**Comment by gnumdk** [comment] 2015-03-04 06:42
Lollypop is not designed to play track outside it's collection so:
- Can't be the default player (as it will only play tracks from your collection)
- Can't play internet radio

This is by design, lollypop is a cover/context based player.

For lyrics, i keep this on my TODO list

For music formats, i use gstreamer so please report your feature request to gstreamer's devs. And tell me if lollypop should look for more supported tracks type (Don't really know what gstreamer supports)

**Comment by heri0nd3** [comment] 2015-03-04 06:51
Here's the supported formats in GStreamer. It'll might help:
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/pwg/html/section-types-definitions.html

**Comment by gnumdk** [comment] 2015-03-04 07:34
Sorry, my response was stupid. It's not about gstreamer but about mutagen. Lollypop need tags and will only support format with tag and with mutagen support.

**Comment by heri0nd3** [comment] 2015-03-04 07:41
Right. It would be nice if Lollypop would like to support metadata (media info) editing with the use of mutagen. That would be a feature request as well.

**Comment by gnumdk** [comment] 2015-03-04 08:02
Yes, was on my first TODO list but some users tell me: "Don't do that, there are tools like easytag for this purpose"

By the way, as you can't access to files, i just plan to add some basic tag editing support in the future...

**Comment by Foggalong** [comment] 2015-03-10 23:48
@gnumdk Hi, I'm from the team developing [Ozon OS](http://ozonos.github.io/) and we're eyeing up possible alternative music players to ship as the default. Lollypop is one of the options we were considering, but we've just come across this:

> Lollypop is not designed to play track outside it collection so [it] can't be the default player

We were wondering if you could give a bit more reasoning as to why this is the case, and also if we could convince you to make it otherwise :)

**Comment by gnumdk** [comment] 2015-03-11 05:36
Do you think about opening multiple externals tracks? 

Adding support for one track is easy but for multiple tracks.... 

For exemple when playing the whole collection even in shuffle, for performance reason, lollypop never load all the files in an array... All is based on albums... 

Will think about this...

**Comment by Foggalong** [comment] 2015-03-11 10:46
Ah its fine. If it's too much work to add it's not a problem, we have other options available :)

**Comment by gnumdk** [comment] 2015-03-11 14:30
Yes, quite hard to implement without doing ugly code... 

Here, i use mpv as default audio player ;)

**Comment by MineyMe** [comment] 2015-03-13 16:16
Not sure if you hadn't already considered this, but it is possible to pass the G_APPLICATION_HANDLES_OPEN flag to GtkApplication as constructor parameter, after which you can register a callback to invoke when the user requests a file to be opened with the application. You could then perhaps just let the file play and show the correct information in the GtkHeaderBar, but do nothing else (i.e. no support for opening multiple files at the same time and have them added to the playback queue if this is too hacky to implement).

I am growing rather fond of Lollypop but would rather ditch my current music player entirely instead of keeping it around for playing single files.

**Comment by gnumdk** [comment] 2015-03-25 14:15
@Foggalong Opening files with lollypop is available in git ;)

**Comment by me4oslav** [comment] 2015-03-25 16:47
@gnumdk Another Ozon (and Numix) guy here. In which branch in the functionality to open file with lollypop implemented?

**Comment by gnumdk** [comment] 2015-03-25 17:49
In master

**Comment by me4oslav** [comment] 2015-03-25 18:08
@gnumdk So, I compiled master (autogen, make and make install) and when I try to start the player I get this:
[me4oslav@localhost lollypop]$ lollypop
/usr/lib64/python3.4/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.4/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 44, in <module>
    app = Application()
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 63, in __init__
    Objects.db = Database()
  File "/usr/local/lib/python3.4/site-packages/lollypop/database.py", line 78, in __init__
    self._set_popularities(sql)
  File "/usr/local/lib/python3.4/site-packages/lollypop/database.py", line 120, in _set_popularities
    WHERE artists.rowid == albums.artist_id")
sqlite3.OperationalError: no such table: albums
[me4oslav@localhost lollypop]$

**Comment by gnumdk** [comment] 2015-03-25 19:51
Try to remove .local/share/apps/lollypop/lollypop.db

**Comment by me4oslav** [comment] 2015-03-25 19:53
Kinda hard to do that because 
![screenshot from 2015-03-25 21 52 50](https://cloud.githubusercontent.com/assets/1658870/6833953/4f3888c0-d339-11e4-85ba-fd5e2846aca7.png)

**Comment by me4oslav** [comment] 2015-03-25 19:59
Ok, I deleted "lollypop.db" from ~/.local/share/lollypop and started the player again and Im getting the same error.

**Comment by gnumdk** [comment] 2015-03-25 22:13
Fixed in master i hope...

**Comment by me4oslav** [comment] 2015-03-25 22:26
Will try when I wake up. Like 5 hours from now. :)

**Comment by gnumdk** [comment] 2015-03-27 07:22
@heri0nd3 =>  All gstreamer supported formats are working in lollypop now ;) But i can't test :-/

**Comment by gnumdk** [comment] 2015-04-20 12:01
For the lyrics, it seems that there is not free API available in the web... So, i will add a link too http://lyrics.wikia.com somewhere in the ui.

**Comment by MineyMe** [comment] 2015-05-01 17:55
I see you're working on radio support right now. I already tried it and it is very nice already (was the last feature I needed to replace my current audio player with Lollypop entirely).

Not sure if this is something you're still planning, but I noticed that other players like DeaDBeeF can somehow fetch a track title from the stream itself (it is updated as soon as the stream actually starts playing). The title is usually something like **Artist - Song of artist**.

**Comment by gnumdk** [comment] 2015-05-01 19:02
Any stream exemple?

**Comment by MineyMe** [comment] 2015-05-01 19:08
Yessir, pretty much all internet radio's I've used up until now do this, not sure if it's something specific to those radio's:

An example: http://67.213.213.143:8048

**Comment by gnumdk** [comment] 2015-05-01 19:40
I will add this as an option per radio as many stream just send garbage as: "RADIO NAME - RADIO NAME" :)

**Comment by MineyMe** [comment] 2015-05-02 11:24
I see you've managed to find it, thanks!

I just noticed a bug when playing radio's that are not available, for example: http://newsletter.frontiers.it:8000/live.mp3 This radio is currently offline, but Lollypop completely freezes when attempting to play it; it should probably just stop trying (show a notification or error via a GtkInfoBar perhaps?) or skip ahead to the next radio.

I also see the back and forward buttons have been disabled for radio's, but would it perhaps be interesting to allow for these buttons to skip ahead and back between available radio stations only (i.e. then you can "skip to another radio station" via MPRIS just like you would in a car radio :P).

**Comment by gnumdk** [comment] 2015-05-02 11:27
The freeze bug seems to be a gstreamer bug :-( Nothing i can do (i think)

**Comment by gnumdk** [comment] 2015-05-02 11:32
Ok, it's a bug in totem.plparser, will try to find a way to fix this...

**Comment by MineyMe** [comment] 2015-05-02 18:24
Thanks, that seems to have done the trick... and away goes my current media player ;-).

**Comment by MineyMe** [comment] 2015-05-10 19:03
I don't know if something changed recently, but the feature that showed the metatags of tracks from radio streams seems to have disappeared in the latest Git version; it used to take a few seconds for the metatag to show up (which was fine), but now it seems to never show up at all and just keeps displaying the name of the radio.

**Comment by gnumdk** [comment] 2015-05-13 08:05
I close this one... LyricWiki API is now closed, no way to get lyrics from it...

**Closed by gnumdk** 2015-05-13 08:05 UTC
