### ISSUE TITLE
Controls from Sound menu not working on Ubuntu Xenial

### ISSUE THREAD

**Issue by andreisusanu** [gnumdk/lollypop#604] opened 2016-05-01 07:09 UTC
I have a fresh installed Ubuntu Xenial. After I've installed Lollypop, I've noticed that the control buttons from the operating system sound menu are not working for Lollypop.
Please notice that the same control buttons are working for other players (Rhythmbox)

[screenshot](http://s32.postimg.org/wpz417cut/lollypop_controls_ubuntu_xenial.png)

I'm running version 0.9.100 of Lollypop on Ubuntu 16.04 amd64.

Please check this problem. Let me know if I can provide more details on this.

Thanks and greetings from Romania,

**Comment by gnumdk** [comment] 2016-05-01 10:55
Strange, works here on Ubuntu 14.04/Eos and Ubuntu 16.04

**Comment by gnumdk** [comment] 2016-05-01 10:56
What is not working? Prev/Play/Next ?

**Comment by andreisusanu** [comment] 2016-05-01 12:02
Yes, that is correct.

Please find more details by watching the next video: [Demo](https://youtu.be/hnYeks_E-es)

**Comment by gnumdk** [comment] 2016-05-01 13:22
Can't reproduce :-/

**Comment by andreisusanu** [comment] 2016-05-01 13:25
How  can I help? What details can I provide?

Please notice that this problem occurs on both my computers. Both are using Ubuntu 16.04.

**Comment by gnumdk** [comment] 2016-05-01 13:28
maybe try different settings (shuffle, party, ...)

**Comment by gnumdk** [comment] 2016-05-01 13:51
Ok, happen when "remember state" is off

**Comment by andreisusanu** [comment] 2016-05-01 13:55
I've played at the settings, and now it's working. I cannot reproduce it anymore.

I've tried with and without restore state... cannot reproduce it anymore :)

Something is fishy there. Have fun fixing it!

Thanks!

**Comment by gnumdk** [comment] 2016-05-01 13:58
Fixed in git

**Closed** 2016-05-01 13:59 UTC

**Comment by andreisusanu** [comment] 2016-05-01 17:13
Upgraded to 0.9.101. Fix confirmed. Thank you very much for your work!
