### ISSUE TITLE
Hide side pane

### ISSUE THREAD

**Issue by chetanpm** [gnumdk/lollypop#849] opened 2016-12-13 17:21 UTC
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
- Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
- Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
- Showing bitrate

BUG MAY BE REJECTED IF MISSING:
-Lollypop version: 0.9.223
-Gtk Version: 3.22
-Linux distribution: Arch linux

-Describe your bug here:

A button to show or hide side panel makes the player much elegant visually.

I have to change paned-mainlist-width key in dconf-editor to zero. A button in the top removes this minor annoyance.

**Comment by gnumdk** [comment] 2016-12-14 08:58
Sorry, wontfix. By design.

**Comment by chetanpm** [comment] 2016-12-14 09:32
uninteresting response :s 

hiding and showing button wouldn't make the design any different. It only makes it more usable.

Its your project anyways, do as you choose fit :)

**Comment by gnumdk** [comment] 2016-12-14 17:52
Adding a button is not making things more usable ;)

**Comment by chetanpm** [comment] 2016-12-15 10:13
more cleaner, not more usable I mean :laughing: 

I understand people have genereal tendency to not agree, I thought something like this: [https://drive.google.com/open?id=0B4IetJnNu09fWGdIa0JVTS1iTkE](url) though hardwork, can make the application stand out midsts the ocean of other media player applications.
At the end of the day, every player does the playing and managing mostly similarly. cleaner homepage presentation gives a polished impression, enhancing the user experience.

I hate too many buttons in design, but when one button could mask so much of other clutter to present a clean experience, I would give it a thought..
Its either a headerbar button or a view option in application menu. A choice to show or hide is a very meaningfull power to an user made possible through open source applications.

**Comment by gnumdk** [comment] 2016-12-15 15:00
But how can you use application if it is hidden, lollypop is designed around this pane!

**Comment by chetanpm** [comment] 2016-12-15 16:12
Every application serves one main purpose. media player's purpose besides playing well is to present the media well for playing (no obstructions). Nobody see their application in their daily usage and say: 'hmmm I love the way I have all these options the application have for me to choose'. This is the basis for "Dieter rams" very famous minimal design philosophy.

It also based in the reality where people always prefer one view. Either all their songs listed or all the albums with covers or something else they like. And they tend to set that to their default view and stick with it. At these instances, the side pane is an extra, consuming my screen real estate.
Other instances where they decide to change their source to listen to internet radio, or some other playlist view, they push one button to show the hidden pane and reveal all these concealed options.

Design revolves around the main purpose buddy. Never around the features. Pane is a feature not the purpose of the application.

**Comment by bil-elmoussaoui** [comment] 2016-12-15 16:26
You can add a shortcut to hide/show the pane

**Comment by gnumdk** [comment] 2016-12-19 12:43
Got an idea...

**Comment by gnumdk** [comment] 2016-12-19 13:43
But not working as I wanted... Tried adding a button along side the list but conflicts with paned drag zone and looks bad... So go for @bil-elmoussaoui proposition.

**Closed** 2016-12-19 13:57 UTC
