### ISSUE TITLE
org.gnome.Lollypop.appdata.xml url not found 

### ISSUE THREAD

**Issue by martinkg** [gnumdk/lollypop#1160] opened 2017-07-12 09:23 UTC
BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: lollypop-0.9.244
- GNOME/GTK+ versions: gnome-2.32.1
- GNU/Linux distribution: Fedora 25

### Bug/Feature
when checking the  file org.gnome.Lollypop.appdata.xml it reports the following error message:

```
$ appstream-util validate-relax ./noarch-redhat-linux-gnu/data/org.gnome.Lollypop.appdata.xml
./noarch-redhat-linux-gnu/data/org.gnome.Lollypop.appdata.xml: FAILED:
? url-not-found         : <screenshot> url not found [https://raw.githubusercontent.com/gnumdk/lollypop-data/master/mainsmall.jpg]
Validation of files failed
```

**Comment by Pointedstick** [comment] 2017-07-13 06:21
Duplicate of https://github.com/gnumdk/lollypop/issues/1148

**Comment by gnumdk** [comment] 2017-07-13 06:48
Fixed

**Closed by gnumdk** 2017-07-13 06:48 UTC
