### ISSUE TITLE
Artistsorting and capitalizing

### ISSUE THREAD

**Issue by kronstadt21** [gnumdk/lollypop#1051] opened 2017-04-30 16:31 UTC
If I have two different artists with the same name, let's say ALMA and Alma they will be sorted under ALMA or Alma depending on which artist is added to the library first.

Would it be possible to make lollypop's sorting to strictly respect capitalizing when organizing database/library?

• Lollypop version: 0.9.231
• Linux distribution: Ubuntu 17.04

**Comment by julianrichen** [comment] 2017-05-01 01:50
I would say it's a feature, it forces you to tag your music consistently :p

If a feature like this is added could it be a switch instead of a default?

**Comment by gnumdk** [comment] 2017-05-01 09:30
Yes, not sure about this one because it will be a regression for most users (me first).

**Comment by gnumdk** [comment] 2017-05-02 06:29
Yes, but musicbrainz tags are not official tags...

**Comment by kronstadt21** [comment] 2017-05-02 11:30
Ok. Well I still think lollypop should strictly respect capitalization, but if you consider it a regression I'll have to respect that. Been searching for a general solution to separating artists with the same name without any luck. Guess I will have to separete them with ugly addenda to the tags...

**Comment by gnumdk** [comment] 2017-05-02 21:11
Not closing, I understand it's an issue, will try to fix it

**Comment by kronstadt21** [comment] 2017-05-05 08:42
Yes, and thinking about I'm surprised that there's no official id3 tag to differentiate between artists with the same name. I.e a secondary artist tag to resort to. It's a tricky issue although not a big one.

**Comment by michael-rapp** [comment] 2017-07-17 18:07
I also encountered this issue. Maybe a viable solution is to differentiate between albums of artists with the same (case-insensitive) name, if their genres are different. At least this would be a descent solution for my use case.

**Comment by Vaesper** [comment] 2017-07-18 10:53
I don't think that works as a general solution, artists can vary between genres between (or even within) albums.

**Comment by gnumdk** [comment] 2017-07-18 12:51
@Vaesper You are right, I have artist with multiple genres ;)

**Comment by gnumdk** [comment] 2017-09-13 13:04
@kronstadt21 And what about doing the same as Wikipedia? https://fr.wikipedia.org/wiki/Alma_(chanteuse)

**Comment by gnumdk** [comment] 2017-09-13 13:04
Adding a suffix...

**Comment by kronstadt21** [comment] 2017-09-13 14:45
Wouldn't it be possible to use the artistsortorder and albumartistsortorder tags to differentiate between artists so that artists are grouped "strictly" if sortorder is present and "sloppy" if not present? Maybe in conjunction with a setting to expose the possibility.

**Comment by gnumdk** [comment] 2017-10-12 09:38
Ok, will close this one because I think it's not possible even using musicbrainz artist id:
- An album can have multiple artists and multiple albums artists
- There is no way to associate a musicbrainz tag in this case

So it will be a broken feature... So only solution, modify artist name by hand, sorry for that.
But I will add a check for ALMA special case: full uppercase.

**Comment by gnumdk** [comment] 2017-10-12 10:05
Simple patch, @kronstadt21 please test and confirm there is no regression ;)

**Closed** 2017-10-12 10:05 UTC
Labels: enhancement

**Comment by kronstadt21** [comment] 2017-10-12 22:34
Ok, tested it (had to get newer version of meson to build). And it works. I now have two Alma/ALMA.
![skarmbild fran 2017-10-13 00-31-12](https://user-images.githubusercontent.com/22260777/31522472-3095401c-afae-11e7-97cc-f2f542517cf4.png)
Hurray!

**Comment by gnumdk** [comment] 2017-10-13 05:08
Little tip:
- You can separate "album artist" tags for Alok, Brunon Martini allowing you to have one entry per artist
- If it's an album with Bruno Martini featuring, just move it to artist tag and then it will be shown in track list

**Comment by kronstadt21** [comment] 2017-10-13 07:31
Thanks, but it's actually a single, a collaboration with Alok, Bruno Martini & Zeeba. I never seperate the tags in artist or albumartist fields. I was kind of surprised by your comment above about artist and albumartist tags could contain multiple artists. Especially the albumartist part. I mean if you split the tags and then, when playing the album you wouldn't get the information that it's actually, in this case, three artists involved. The only tag that I seperate is the genre for like subgenres. I guess we all have our own ideas of how things should work, right!?
