### ISSUE TITLE
No more artist name/song name info in sound appletafter last update

### ISSUE THREAD

**Issue by ghost** [gnumdk/lollypop#908] opened 2017-01-14 06:38 UTC
• Lollypop version: 0.9.226
• Gtk Version: 3.18.9-1ubun
• Linux distribution: Linux Mint 18.1 Cinnamon

after the .226 update i no longer have cover photos or artist/song info in my panel info.  i can control Lollypop fine thru the applet and lollpop works fine stand alone..

**Comment by scde** [comment] 2017-01-14 12:00
I think this is a duplicate of #907

**Comment by QuakeString** [comment] 2017-01-14 14:00
- Lollypop version: 0.9.226
- Unity Version: 7.5.0
- Ubuntu 16.10

1. cant see Lollypop at unity sound applet, so cant control from there. 
2. playing music is just file.
3. I don't know its bug or not regarding preview song, I think there should have at least 250ms delay to play preview, for me some if mouse hove on multiple songs, and multiple songs start playing, kinda annoying. I had to disable this function.

**Comment by kronstadt21** [comment] 2017-01-14 19:52
Have the same issue and same versions as QuakeString. CoverGloobus works fine to contol Lollypop. Issue appeared in previous version I believe. Also noted that the program-icon wasn't themed but fell back to default with this update.

**Comment by gnumdk** [comment] 2017-01-14 21:39
OK, thanks @konstradt21, you're right, issue was in previous versions, will fix it as soon as possible.

**Comment by gnumdk** [comment] 2017-01-15 19:41
Should be fixed.

**Closed by gnumdk** 2017-01-15 19:41 UTC
