### ISSUE TITLE
Track objects in Artist view prevent touchpad scrolling

### ISSUE THREAD

**Issue by SolarLiner** [gnumdk/lollypop#1220] opened 2017-08-21 05:06 UTC
May be related to slow scrolling.

![](https://thumbs.gfycat.com/EverlastingNeighboringKilldeer-size_restricted.gif)

### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: GNOME 3.24 - GTK 3.22
- GNU/Linux distribution: Ubuntu GNOME 17.04

### Bug/Feature
When hovering over tracks  or albums, scrolling *with a touchpad* gets blocked (happens while already scrolling too).

**Comment by gnumdk** [comment] 2017-08-21 09:37
Why are you using Xwayland? Lollypop works on Wayland.

**Comment by SolarLiner** [comment] 2017-08-21 09:41
AFAIK this is how GDM opens GNOME on Wayland.  
Unless I've been using true Wayland all this time and I'm then surprised at how many applications are supported. In which case, this bus is happening on real Wayland.

Anyway to tell exactly which compositor it used?

**Comment by gnumdk** [comment] 2017-08-22 09:07
Can't reproduce here, scrolling is working...

**Comment by SolarLiner** [comment] 2017-08-25 15:32
So scrolling lags (on Xorg) and Wayland while using a touchscreen. When using a mouse, scrolling is fine.

I'll update the title.

**Comment by gnumdk** [comment] 2017-08-25 16:32
Does not happen here on my laptop, I do not have a mouse...

**Comment by SolarLiner** [comment] 2017-08-25 17:09
Which distro are you using? I'm on Ubuntu GNOME 17.04.

**Comment by gnumdk** [comment] 2017-08-25 18:24
ArchLinux and Fedora

**Comment by gnumdk** [comment] 2017-09-06 09:30
@SolarLiner Can you try with Adwaita?

**Comment by gnumdk** [comment] 2017-09-13 14:45
https://bugzilla.gnome.org/show_bug.cgi?id=767713

Should be fixed since a lot of time... Ubuntu bug.

**Closed by gnumdk** 2017-09-13 14:45 UTC

**Comment by gnumdk** [comment] 2017-10-30 17:47
@SolarLiner Look at #1279 ;)
