### ISSUE TITLE
Theme change clicking on 🎜

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#1055] opened 2017-05-10 10:11 UTC
### Specs
• Lollypop version: 0.9.231
• GTK version: GNOME 3.24/GTK+3.24
• GNU/Linux distribution: Fedora 26

### Bug
As a continuation of #1035.
With dark theme, I click on 🎜 button, and the theme change to grey theme.
That's awesome 😸

**Comment by M5oul** [comment] 2017-05-10 10:23
It seems it's implement to change theme with party mode?
Mine is going grey when it's on party mode.

**Comment by gnumdk** [comment] 2017-05-10 10:41
What is your theme, does not happen with Adwaita here...

**Comment by M5oul** [comment] 2017-05-10 17:39
My theme is Adwaita.

**Comment by gnumdk** [comment] 2017-05-10 18:25
Strange, same distro, same theme...

**Comment by gnumdk** [comment] 2017-05-10 18:26
A screencast please?

**Comment by M5oul** [comment] 2017-05-10 19:13
I am not able to do a screencast.
Here is some screenshots:
![bildschirmfoto vom 2017-05-10 20-38-32](https://cloud.githubusercontent.com/assets/4758871/25916541/42dbca42-35c5-11e7-88d4-e106c42f6b78.png)
![bildschirmfoto vom 2017-05-10 20-38-49](https://cloud.githubusercontent.com/assets/4758871/25916567/61b8a426-35c5-11e7-93c2-f9a14fa2d523.png)

**Comment by bil-elmoussaoui** [comment] 2017-05-10 22:38
It seems to be a feature not an issue
Duplicate of https://github.com/gnumdk/lollypop/issues/188

**Comment by gnumdk** [comment] 2017-05-11 05:47
"With dark theme, I click on 🎜 button, and the theme change to grey theme."

@M5oul That"s not what your screenshot is showing, you are not using dark theme by default.

**Comment by gnumdk** [comment] 2017-05-11 05:47
La Fraction, excellent choix ;)

**Comment by M5oul** [comment] 2017-05-11 05:59
> That's not what your screen shot is showing, you are not using dark theme by default.

I am using dark theme. GNOME is configured to use dark theme. And Lollypop follow this as #1035.

![bildschirmfoto vom 2017-05-11 07-56-25](https://cloud.githubusercontent.com/assets/4758871/25934689/a76a06cc-361f-11e7-9d65-216808630f97.png)

---

>La Fraction, excellent choix ;)

Thanks!

**Comment by M5oul** [comment] 2017-05-11 06:01
If it's already dark. It should stay dark on _Party mode_.

**Comment by gnumdk** [comment] 2017-05-11 10:11
But it stays dark here. F26 too.

**Comment by gnumdk** [comment] 2017-05-16 08:54
When you leave party mode! Please be explicit :p

**Closed** 2017-05-16 08:55 UTC

**Comment by M5oul** [comment] 2017-05-17 13:53
Thanks for the fix.
