### ISSUE TITLE
CollectionScanner NOT NULL check prevents populating music library

### ISSUE THREAD

**Issue by mmccoy37** [gnumdk/lollypop#1064] opened 2017-05-11 22:31 UTC
• Lollypop version: 0.9.233
• Gtk Version: 3.22.11-1
• Linux distribution: debian stretch

Collection Scanner fails with NOT NULL check failed if any songs in library are missing attribute 'message'. (hopefully this was a mistake, because why would force that EVERY tag is filled?)

this prevents anything from the library being populated.

`matt@pc:~$ lollypop
CollectionScanner::__scan(add): NOT NULL constraint failed: albums.mtime file:///home/matt/Music/Beethoven/00%20German%20Dance%20-%20Rondo.mp3
CollectionScanner::__scan(): 'IntegrityError' object has no attribute 'message'

`

Thanks,
Matt

**Comment by gnumdk** [comment] 2017-05-12 08:24
Your db is broken du to update 20 not done. Strange :-1: 

$ gsettings set org.gnome.Lollypop db-version 19

Should fix your issue. Did you downgrade Lollypop or restore the db?

**Comment by mmccoy37** [comment] 2017-05-12 14:53
changing db version doesnt seem to fix. ill try an earlier lollypop build though

**Comment by gnumdk** [comment] 2017-05-12 16:11
Can you send my your db by email

**Comment by gnumdk** [comment] 2017-05-12 20:00
Is it your first lollypop installation? Db is empty and I can't understand how it can be like this!

removing lollypop.db should fix your issue.

**Comment by gnumdk** [comment] 2017-05-16 09:07
Closing this one, sorry but without more information, I can't guess what happened.

Can't reproduce.

**Closed by gnumdk** 2017-05-16 09:07 UTC
