### ISSUE TITLE
External track won't play when internal track is playing.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#201] opened 2015-07-12 10:18 UTC
Hello

I'm experiencing a rather strange issue with Lollypop that I didn't discover until I had some external tracks to play recently; I can reproduce as follows:

1. Start Lollypop.
2. Play any track from your (internal) library.
3. Navigate using your file browser to an external track (i.e. not in your library) and open it with Lollypop.

Lollypop will now seemingly 'ignore' the command and will not play the track. However, if either you close Lollypop first before you play the track or it was already playing another external track, it works just fine. I've also noticed that in some rare cases, the bug doesn't appear at all, but I can mostly consistently reproduce it.

Hope you can reproduce it. I also see no errors popping up in the console.

Thanks in advance

**Comment by gnumdk** [comment] 2015-07-14 11:33
Cannot reproduce here... Does't it happen on first internal track?

**Comment by hotoiledgoblinsack** [comment] 2015-07-14 15:55
Ah, at first it seemed as if I couldn't reproduce it anymore, but I've gotten so used to enable stop after current that I forgot to mention that it was on ;-). Apparently, this only happens when the track currently playing has 'stop after current' enabled (tested in 0.9.39).

**Comment by gnumdk** [comment] 2015-07-14 16:42
Fixed by https://github.com/gnumdk/lollypop/issues/202

**Closed** 2015-07-14 16:42 UTC
