### ISSUE TITLE
Touchscreen: bottom panel can be resized even when it is hidden.

### ISSUE THREAD

**Issue by alexskc** [gnumdk/lollypop#200] opened 2015-07-11 05:04 UTC
On a touchscreen, it's quite easy to end up not dragging to scroll, and instead resizing the invisible bottom panel by grabbing roughly where you'd expect its edge to be.

**Comment by gnumdk** [comment] 2015-07-11 08:17
What is the invisible bottom panel?

**Comment by alexskc** [comment] 2015-07-11 08:35
It's kind of hard to explain/demonstrate.

I've recorded a video here. https://www.youtube.com/watch?v=xULfdRWGh0Q

Hopefully the mouse movement should give you an idea of what I'm doing.

**Comment by gnumdk** [comment] 2015-07-14 11:48
The panel is not invisible (but hidden) and if it is poping out, it's because you are clicking on an album while dragging to scroll...

**Comment by alexskc** [comment] 2015-07-14 12:03
Sorry if I wasn't being clear. What I'm doing in the video is:

Opening the bottom panel by clicking on an album, making it as small as possible.
Hiding it.
Grabbing/dragging the top edge of the bottom panel to resize it, despite the fact that it is hidden.
Clicking on another album to demonstrate that it has been resized.

The bottom panel should not be resizable while it is hidden.

As far as I can tell, this is only an issue with touch input. I can't do the same thing with a mouse.

**Comment by gnumdk** [comment] 2015-07-14 13:53
>making it as small as possible.

Can be smaller than cover

> Grabbing/dragging the top edge of the bottom panel to resize it, despite the fact that it is hidden.
Top edge isn't visible when panel hidden

**Comment by alexskc** [comment] 2015-07-14 14:22
>Top edge isn't visible when panel hidden

Yes, but it's still grab-able, and that is the issue here.

**Comment by gnumdk** [comment] 2015-07-14 16:38
I can't reproduce issue here, no grab-able when hidden... (even with my xps with touchscreen)

**Comment by gnumdk** [comment] 2015-07-16 06:54
>Hiding it.

How do you do this step?

**Comment by alexskc** [comment] 2015-07-16 11:30
By clicking again on an album I already clicked on. (with click again to play disabled)

**Comment by gnumdk** [comment] 2015-07-16 13:42
Ok, so like me :-( Not a side bug...

When panel is hidden, do you see cursor changing when on paned separator? Do you see paned separator?

**Comment by alexskc** [comment] 2015-07-16 13:56
I don't see the panel separator. And I don't see the mouse cursor at all because I'm using thouchscreen. I'm completely unable to recreate the issue using a mouse/pointer.

**Comment by alexskc** [comment] 2015-07-16 14:04
I'm starting to wonder if this might not be caused by how different Gnome/GTK versions handle touch input or something... To be sure, I'm on Gnome 3.16.2

**Comment by gnumdk** [comment] 2015-07-16 14:37
I'm on archlinux with an XPS 13 + touchscreen and can't reproduce :-(

**Comment by alexskc** [comment] 2015-07-16 15:30
Tried it on another computer with GTK Inspector's "Simulate touchscreen," and couldn't reproduce there, either.

But on my usual computer I can reproduce it easily every time. Really strange. :/

**Comment by gnumdk** [comment] 2015-07-20 06:58
Same distro on two computers?

**Comment by gnumdk** [comment] 2015-08-05 14:54
I close this one as i'm sure it's not an issue in Lollypop.

**Closed by gnumdk** 2015-08-05 14:54 UTC
Labels: question
