### ISSUE TITLE
Can't access lyrics sometimes

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#1087] opened 2017-05-20 07:13 UTC
### Environement
- Lollypop version: 0.9.234
- GNOME version: 3.24
- GNU/Linux distribution: Fedora 26 Alpha

### Bug
When reading lyrics of many songs. When music change, I update the lyrics with the refresh button and sometimes I can't access the web page with following message:
```bash
Error performing TLS handshake: An unexpected TLS packet was received.
```

**Comment by gnumdk** [comment] 2017-05-20 08:05
Strange, this is not a lollypop bug. But I do not have such issue in eolie, so will give a look

**Comment by gnumdk** [comment] 2017-05-20 16:59
Tested about 100 songs and can't reproduce.
Fedora 26 too.

I let this bug report open, I'm about to release https://gnumdk.github.io/eolie-web/ soon and you should be able to reproduce issue (and it's a bad news for a web browser if it happens)

**Comment by gnumdk** [comment] 2017-05-20 17:02
Hmm, but you are using Eolie! https://github.com/gnumdk/eolie/issues/27 :-)

You do not have the issue with Eolie? Are you using flatpak version of Lollypop?

**Comment by M5oul** [comment] 2017-05-22 11:05
>You do not have the issue with Eolie?

Nope. For the little I used it it's ok.

> Are you using flatpak version of Lollypop?

Nope, I use the Copr repository.

---

Could the issue come from the website used to retrieve lyrics?

**Comment by gnumdk** [comment] 2017-05-23 15:40
Don't know but the issue is not in Lollypop so I'm closing this one.

ps: ça ressemble quand même à une erreur réseau, au niveau de webkit. Impossible à reproduire pour moi avec Free(ADSL), Sosh(4G) et Renater.

**Closed by gnumdk** 2017-05-23 15:40 UTC
