### ISSUE TITLE
Music updater continue to run for quite a long time after exit

### ISSUE THREAD

**Issue by kelvan** [gnumdk/lollypop#263] opened 2015-09-05 10:41 UTC
Using f8b67cf

When quitting lollypop right after starting it, it continues to indexing my Music for about a minute.
And then it dies with a segfault (no python errors shown [debug mode])
Segfault happens often also without indexing in progress.

**Comment by gnumdk** [comment] 2015-09-07 11:29
Can't reproduce "indexing my Music for about a minute"

**Comment by gnumdk** [comment] 2015-09-07 13:48
>When quitting lollypop right after starting it

And when not quitting, does it scan music for about one minute?

**Comment by kelvan** [comment] 2015-09-08 12:00
Yes, it just don't stop the scan process when quitting, not a problem with a small library, but with a lot of music it produces much I/O after gui disappeared.

**Comment by gnumdk** [comment] 2015-09-08 15:33
The question is more about: "Why lollypop always hangs on scan"

Because, lollypop stop scan when quitting, seems that gstreamer is failing on some files...

**Comment by gnumdk** [comment] 2015-09-09 06:57
Can you show me lollypop -d output

**Comment by gnumdk** [comment] 2015-09-14 07:12
ping?

**Comment by kelvan** [comment] 2015-09-15 12:38
sorry, wasn't home a while, can't reproduce on my laptop (small library), I'll try to reproduce in the afternoon.

**Comment by kelvan** [comment] 2015-09-16 17:57
I'm not able to reproduce on desktop with latest git version.
Just segfault at close:
[1]    22933 segmentation fault (core dumped)  lollypop -d

**Comment by gnumdk** [comment] 2015-09-16 19:48
Ok, i close this one...

Segfault comes from python/glib/gtk...

**Closed by gnumdk** 2015-09-16 19:48 UTC
Labels: question
