### ISSUE TITLE
Empty app menu

### ISSUE THREAD

**Issue by michael-rapp** [gnumdk/lollypop#648] opened 2016-06-02 14:14 UTC
I am using Gnome 3.20.2 and sometimes I am encountering a situation where Lollypop's app menu (the one in Gnome's top bar) is empty. In such case, only the option, which allows to quit the application is shown. All other options such like the "Preferences" menu item are gone. You can see this on the screenshot below.

![screenshot from 2016-06-02 16-03-15](https://cloud.githubusercontent.com/assets/6638695/15747712/4de59252-28dc-11e6-81c9-7c6feec01b52.png)

Appearantly the reason for this issue is, that I have the option "Continue playback when closed" enabled in the settings. When the application is closed (with music still playing) and is then opened again afterwards, the menu items are gone.

-Lollypop version: 0.9.107
-Gtk Version: 3.20.6
-Linux distribution: Arch Linux

**Comment by gnumdk** [comment] 2016-06-03 07:33
Not happening here with ArchLinux... :disappointed:

**Comment by gnumdk** [comment] 2016-06-03 07:47
Does it happen everytime with "Continue playback when closed"  on?

**Comment by michael-rapp** [comment] 2016-06-03 11:29
Yes, it always occurs. I then have to kill Lollypop's process and start it again in order to get the menu back. Another thing I noticed is, that the loading indicator next to the app menu is visible for quite a long time when the application is brought back to the front. The app menu is not even clickable while the loading indicator is still shown and when it finally goes away, the app menu is empty.

However, I don't think that this is a Lollypop related bug, anymore. I tried to reproduce it with other applications and I encountered the same problem with the mail application "Geary". Is also runs in background permanently and when I bring it to the front, its app menu entries are gone. I could not find anything about this issue online. Do you have an idea what might be the reason?

**Comment by gnumdk** [comment] 2016-06-03 12:04
Wayland? Startup notification is broken on wayland...

**Comment by gnumdk** [comment] 2016-06-03 12:14
https://bugzilla.gnome.org/show_bug.cgi?id=752258

**Comment by gnumdk** [comment] 2016-06-03 12:15
Will try to find a fix...

**Comment by michael-rapp** [comment] 2016-06-03 12:49
You're right, it only occurs on Wayland. I just tried it out running a X session and all menu items showed up properly.

**Comment by bil-elmoussaoui** [comment] 2016-06-03 13:03
Pushed a fix!

**Closed** 2016-06-03 13:16 UTC
Labels: bug

**Comment by gnumdk** [comment] 2016-06-03 13:20
Not fixing issue here on ArchLinux as XDG_CURRENT_DESKTOP is GNOME on Wayland ;)

But, for me the issue is not in Lollypop, will fix it (if I need to do something) as soon as the issue is fixed in nautilus.

**Comment by bil-elmoussaoui** [comment] 2016-06-03 13:24
@gnumdk Are you sure ? Here it works, i guess his installation is somehow broken and the `XDG_CURRENT_DESKTOP` does not return `gnome-wayland` nor `gnome`
@michael-rapp Can you print the output of this python script 
```python
from os import environ
print(environ.get("XDG_CURRENT_DESKTOP"))

```

**Comment by gnumdk** [comment] 2016-06-03 13:26
No, issue as nothing to do with XDG_CURRENT_DESKTOP...
It's about startup notification broken on wayland for apps running in background (geary, nautilus, ...)

**Comment by gnumdk** [comment] 2016-06-03 13:29
@bil-elmoussaoui Where do you see XDG_CURRENT_DESKTOP == gnome-wayland?

**Comment by bil-elmoussaoui** [comment] 2016-06-03 13:29
@gnumdk https://github.com/jangernert/FeedReader/issues/128#issuecomment-222470643

**Comment by bil-elmoussaoui** [comment] 2016-06-03 13:30
Oh non! i missed up, i thought it was the result of `XDG_CURRENT_DESKTOP`:(

**Comment by gnumdk** [comment] 2016-06-03 13:30
DESKTOP_SESSION is not XDG_CURRENT_DESKTOP

**Comment by bil-elmoussaoui** [comment] 2016-06-03 13:31
See my comment above :) sorry for the mess, you can revert my commit

**Comment by gnumdk** [comment] 2016-06-03 13:32
BTW, as nautilus is broken too, I let this bug as closed...

**Comment by gnumdk** [comment] 2016-06-03 13:35
@michael-rapp Any motivation to report this upstream? :)

**Comment by michael-rapp** [comment] 2016-06-06 12:01
@gnumdk I do not really understand the technical background of this issue's underlying problem. As you seem to know how app menus are implemented and what prevents them from behaving correctly on Wayland, I would rather like to ask you to report the issue instead of reporting it by myself. 

By the way, the value of the variable `XDG_CURRENT_DESKTOP` is `GNOME` on my system when running Wayland. Although I think that this is not relevant anymore...
