### ISSUE TITLE
Lollypop not found

### ISSUE THREAD

**Issue by mehdi-alouane** [gnumdk/lollypop#1162] opened 2017-07-12 21:32 UTC
### Environment
- Lollypop version: 0.9.244-1ppa1ubuntu1.1
- GNOME/GTK+ versions: 3.18.9-1ubuntu3.3
- GNU/Linux distribution: Elementary os Loki

### Bug/ issue
Lollypop not found after updating the OS

**Comment by RODNOTGOD** [comment] 2017-07-13 02:45
same issue

# Environment
  - Lollypop version: 0.9.244-1ppaubuntu1.1
  - GNU/Linux distribution: Ubuntu Gnome 17.04

**Comment by Pointedstick** [comment] 2017-07-13 06:20
Duplicate of https://github.com/gnumdk/lollypop/issues/1148

**Closed** 2017-07-13 06:49 UTC
