### ISSUE TITLE
semi freezing and jerkiness

### ISSUE THREAD

**Issue by johnpiers** [gnumdk/lollypop#788] opened 2016-10-25 09:53 UTC
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

WONTFIX:
- Showing bitrate

-Lollypop version: 0.9.213
-Gtk Version:
-Linux distribution: ARCH Linux (Gnome) 

-Describe your bug here:
Was working fine and now when Lollypop is opened it's all jerky and almost freezes. You can play music no problem, but moving around is problematic because of the semi freezing and jerkiness. I installed this version (0.9.213) thinking it would help but it's just as bad. I'm not sure that it's Lollypop that's causing the problem any ideas would be great. Rolled back the package one at a time to three older versions but also had the same problem. At a bit of a loss as what to look for, perhaps you guys can help. I did a 'lollypop -d' but so much stuff gets produced by the terminal that I was not sure if I should post that here.

Thank you.
Piers

**Comment by johnpiers** [comment] 2016-10-25 09:54
Gtk Version is 3

**Comment by gnumdk** [comment] 2016-10-25 12:51
What top command says?

**Comment by johnpiers** [comment] 2016-10-25 20:20
See nothing unusual in Htop. This from terminal command lollypop -d 
[output-file.txt](https://github.com/gnumdk/lollypop/files/551696/output-file.txt)

Thanks.

**Comment by gnumdk** [comment] 2016-10-26 11:49
Can you do a screencast showing the issue?

**Comment by michael-rapp** [comment] 2016-10-26 17:41
I came here to see, if anyone is having the same problems and appearantly it is the case...Since a few days scrolling in Lollypop's album view is really slow. The view freezes for two or three seconds and then immediately jumps to the new position. Resizing the window also causes the UI to freeze. Scrolling in the list of artists or genres works fine though.

I am using Lollypop 0.9.211 on Arch Linux and don't remember an update in the past days. However, GTK3 got updated and maybe it has something to do with the bad performance. Here are the last GTK3 updates according to the log files of my package manager:

```
$ tail -500 /var/log/pacman.log | grep gtk3
[2016-10-23 21:19] [ALPM] upgraded gtk3 (3.22.1+8+ge11df6c-2 -> 3.22.1+67+gffb1ac5-1)
[2016-10-23 21:19] [ALPM] upgraded gtk3-print-backends (3.22.1+8+ge11df6c-2 -> 3.22.1+67+gffb1ac5-1)
[2016-10-24 03:08] [ALPM] upgraded gtk3 (3.22.1+67+gffb1ac5-1 -> 3.22.1+69+ga1115c0-1)
[2016-10-24 03:08] [ALPM] upgraded gtk3-print-backends (3.22.1+67+gffb1ac5-1 -> 3.22.1+69+ga1115c0-1)
```

**Comment by johnpiers** [comment] 2016-10-26 18:59
@michael-rapp you are describing exactly the symptoms that I am experiencing. 

At this point the only thing I can think that it could be, is that the Nvidia version that ARCH compiled, a revision of the Nvidia drivers (nvidia 370.28-2) is the cause of the problem. So I'm not really sure if this has anything to do with the issue at hand, it's a bit of guesswork. I've not rolled it back to nvidia 370.28-1 because there may have been a reason that this was done because of the latest stable kernel compiled by ARCH (4.8.4-1-ARCH)

**Comment by michael-rapp** [comment] 2016-10-26 19:04
I use an Intel GPU and don't have the nvidia package installed...

I have further noticed, that scrolling performance is only bad when using the scroll wheel. When draging the slider at the right, the performance is alright.

**Comment by johnpiers** [comment] 2016-10-26 19:08
OK fair comment, then it not what's causing the problem! The scrolling bit, the same my side but even using the slider it's crap, completely jerky as well as mini freezes also artwork (when you first open Lollypop) hasn't loaded properly etc.

**Comment by gnumdk** [comment] 2016-10-27 08:04
Strange, ArchLinux too, Intel GPU and AMD GPU and no freeze :-/

**Comment by gnumdk** [comment] 2016-10-27 08:44
> that scrolling performance is only bad when using the scroll wheel.
@michael-rapp In album view or in artist list?

**Comment by johnpiers** [comment] 2016-10-27 11:17
Ok, this is what I've found. As regards @michael-rapp mentioning Gtk3, there were updates for this a little while ago. Today. It changed nothing, scrolling and slider stil mini freezes and jerky. I then turned the music  "auto-update" off and the problem solved. Shut Lollypop down after turning it back while prog is running and the errant behaviour is back turn it off again, restart Lollypop and it's OK. Go figure! Thanks.

**Comment by gnumdk** [comment] 2016-10-27 11:28
When automatic update is on, Lollypop monitor changes in all directories from collection (inotify)... Seems something is wrong here... Do you have an application like seafile, dropbox running?

**Comment by johnpiers** [comment] 2016-10-27 11:43
@gnumdk

Hi. I do have seafile on the PC but checked with Htop and it's not running and neither is Dropbox. I had this on the PC for a while but haven't seen any strange behaviour from Lollypop prior to this! Thanks for all the effort, appreciate all your trouble.

**Comment by gnumdk** [comment] 2016-10-27 16:09
Not fixed...

**Comment by gnumdk** [comment] 2016-10-27 16:18
Bug is in GTK 3.22, do not happend on Ubuntu 16.04...

**Comment by michael-rapp** [comment] 2016-10-27 16:29
> I then turned the music "auto-update" off and the problem seems to be solved.(After restarting the program) Shut Lollypop down after turning it ("auto-update") back on while prog is running and after a restart the errant behaviour is back, turn it off again, restart Lollypop and it's OK.

I just tested this out and I can confirm it. When auto-update is turned of, the issue does not occur. I have dropbox and insync running.

**Comment by gnumdk** [comment] 2016-10-27 16:41
Ok, comes from inotify ^^

**Comment by gnumdk** [comment] 2016-10-27 16:46
/var/cache/pacman/pkg/gtk3-3.22.1-1-x86_64.pkg.tar.xz
Fix the issue. So report to ArchLinux, then to GNOME...

**Comment by gnumdk** [comment] 2016-10-27 16:50
If someone want to bisect GTK...

**Comment by gnumdk** [comment] 2016-10-29 14:34
Regression due to https://git.gnome.org/browse/gtk%2B/commit/?id=12579fe

**Comment by gnumdk** [comment] 2016-10-29 14:34
https://bugzilla.gnome.org/show_bug.cgi?id=767713#c17

**Comment by gnumdk** [comment] 2016-10-29 14:47
Fixed

**Comment by gnumdk** [comment] 2016-10-31 15:46
Not fixed, with all artists view, on my computer, GTK is slow as hell :-(

**Comment by johnpiers** [comment] 2016-10-31 16:08
This version is working fine. lollypop-git 0.9.213.r2.g1c04e1f-1. Perhaps you can take a look and see what's being done differently.

**Comment by gnumdk** [comment] 2016-10-31 17:37
No, it's working fine with small collections...

**Comment by gnumdk** [comment] 2016-10-31 17:49
https://youtu.be/qqxNEaJJHxM
https://youtu.be/84Q2JRZNrY8

**Comment by johnpiers** [comment] 2016-10-31 17:52
At the moment I have about 1276 albums with 14486 songs

**Comment by gnumdk** [comment] 2016-10-31 17:53
And what happen if you try to scroll in the "All albums/All artists" view?

**Comment by michael-rapp** [comment] 2016-10-31 18:10
Your video shows exactly the same issue I have when scrolling the "All artists" collection (over 2400 albums). When scrolling in collections with less albums (those for individual genres) the performance is far better. However, when scrolling in the view, which is shown when a single artist is selected, the performance is awful as well (see video). As I mentioned earlier, using the scrollbar is kind of a workaround...this can also be seen in the video.

https://youtu.be/rYvD_4y4I48

**Comment by johnpiers** [comment] 2016-10-31 18:15
@gnumdk It's fine no problems.

**Comment by gnumdk** [comment] 2016-10-31 18:17
Are you sure you are using gtk 3.22.2?

**Comment by gnumdk** [comment] 2016-10-31 18:17
More information here:
https://bugzilla.gnome.org/show_bug.cgi?id=767713#c21

**Comment by gnumdk** [comment] 2016-10-31 18:20
Nothing being done differently, there was no change since this commit...

**Comment by johnpiers** [comment] 2016-10-31 18:22
gtk3-3.22.2+4+gc54f348-1

**Comment by gnumdk** [comment] 2016-10-31 18:23
@michael-rapp Here a fixed Gtk version:
https://github.com/gnumdk/lollypop-data/blob/master/gtk3-3.22.2-2-x86_64.pkg.tar.xz

Install it, blacklist gtk3 upgrade in pacman.conf and wait for news ;)

**Comment by michael-rapp** [comment] 2016-10-31 18:24
@gnumdk Thanks
@johnpiers Are you using Wayland?

**Comment by gnumdk** [comment] 2016-10-31 18:29
@michael-rapp Here occur on Xorg

**Comment by michael-rapp** [comment] 2016-10-31 18:31
@gnumdk I have not tested it on Xorg. I assumed it because of the title ("Fullscreen in wayland is buggy") of this issue: https://bugzilla.gnome.org/show_bug.cgi?id=767713#c21

**Comment by gnumdk** [comment] 2016-10-31 18:32
The issue was fixed by the commit that make lollypop freezing, and it's a general gdk issue.

**Comment by johnpiers** [comment] 2016-10-31 18:32
@michael-rapp No I'm not.

**Comment by gnumdk** [comment] 2016-11-02 12:18
@michael-rapp @johnpiers 
Here you will find a fixed packages with upstream patch. Please install it and report any regression you may find (in gtk apps) here:
https://bugzilla.gnome.org/show_bug.cgi?id=767713

https://github.com/gnumdk/lollypop-data/blob/master/gtk3-3.22.2%2B13%2Bg28ce953-1-x86_64.pkg.tar.xz

**Comment by gnumdk** [comment] 2016-11-14 14:19
Can't do more, fixed on Fedora 25.
ArchLinux user, wait for a fixed GTK... 3.22.4?

**Closed by gnumdk** 2016-11-14 14:19 UTC
Labels: Upstream

**Comment by michael-rapp** [comment] 2016-11-20 13:53
I've updated to gtk3 4.22.4 on Arch yesterday and the issue seems to be gone. Thank you.
