### ISSUE TITLE
Feature request: Option to auto-scroll lyrics

### ISSUE THREAD

**Issue by Pointedstick** [gnumdk/lollypop#1088] opened 2017-05-20 20:49 UTC
### Environment
• Lollypop version: 0.9.233
• Gtk Version: 3.22.11-1.1
• Linux distribution: openSUSE Tumbleweed

### Feature
For songs with lyrics in the ID3 tag, right now you need to manually scroll the lyrics pane to be able to see the current lyrics as the song progresses. It would be really nice if there was a button to make the lyrics view auto-scroll in time with the music. It would scroll slower for a long song, and faster for a short song. This would be an imperfect guess, but probably good enough in most cases, and you could turn it off if you didn't like it or find it accurate.

**Comment by gnumdk** [comment] 2017-05-28 11:10
Sorry wont fix, do some testing, it's really broken by design.

**Closed by gnumdk** 2017-05-28 11:10 UTC

**Comment by Pointedstick** [comment] 2017-05-28 19:43
Huh? What is really broken by design?

**Comment by gnumdk** [comment] 2017-05-29 10:55
Yes, do not works for most of my tracks so it's broken by design...

**Comment by Pointedstick** [comment] 2017-06-15 22:24
That's not what "broken by design" means. It means "We intentionally wrote the feature in what is widely viewed to be the incorrect way (usually because our management insisted upon it)."

Amarok has this feature and it seems to work just fine for pretty much everything I've got. I don't see why it wouldn't work for your songs, unless most of them start or end with five minutes of silence.
