### ISSUE TITLE
Lollypop doesn't recognize the media keys.

### ISSUE THREAD

**Issue by simonbcn** [gnumdk/lollypop#1135] opened 2017-06-23 11:47 UTC
### Environment
- Lollypop version: 0.9.240
- GNOME/GTK+ versions: GNOME Shell 3.24.2 / GTK+ 3.22.16-1
- GNU/Linux distribution: Arch

### Bug/Feature
Sometimes, when Gnome is in sleep (blank screen), Lollypop doesn't recognize the media keys.
I have to unlock screen, bring Lollypop to front and it works.

**Comment by gnumdk** [comment] 2017-06-23 11:52
Gnome issue. Can you reproduce with Gnome Music? If yes, report upstream.

**Comment by gnumdk** [comment] 2017-07-02 13:21
Closing as Lollypop is just listening to DBus signals so it it's not working, the issue is in gsd :-/

**Closed by gnumdk** 2017-07-02 13:21 UTC
