### ISSUE TITLE
When running for a while, Lollypop will 'freeze'.

### ISSUE THREAD

**Issue by hotoiledgoblinsack** [gnumdk/lollypop#223] opened 2015-08-05 20:04 UTC
Hello

This is an issue that might be hard to debug and I'm not even sure it's Lollypop's fault, but I've noticed that sometimes, when I leave Lollypop open for quite some time, it 'freezes', or rather, it goes into 'sleep' mode. I can reproduce with the following steps:

  * Open Lollypop (I usually played some music with it, but I don't think it's required).
  * Play a song and pause it.
  * Close Lollypop and leave it running in the background (using the option to continue playing after closing in the settings dialog).
  * Wait for a while (in the cases I've tested, it was never more than two or three hours).

At this point Lollypop is still running in the background as it should, and the MPRISv2 plugin for gnome-shell is also still correctly displaying that it is running. However, I can no longer interact with Lollypop through MPRIS, pressing any of the buttons will have no effect. Additionally, if I try to start Lollypop again through the command line (to bring up the window), I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 47, in <module>
    app = Application()
  File "/usr/lib/python3.4/site-packages/lollypop/application.py", line 125, in __init__
    self.register(None)
GLib.Error: g-io-error-quark: Timeout was reached (24)
```

Looking in the process monitor, it says that the python3 process that is running Lollypop is in the 'Sleep' (Sl+) state. An strace indicates that it's hanging on

```
futex(0x55f75f8a7888, FUTEX_WAIT_PRIVATE, 0, NULL
```

So somehow, Lollypop or Python has gotten itself stuck somewhere, but I have no idea why this happens or if it's even these two causing the issue. Killing the python3 process and starting Lollypop again makes everything work again as expected (including MPRIS).

This is not really a large issue for me, but I just wanted to report this to see if you may have an idea what is causing this.

Thanks in advance

**Comment by gnumdk** [comment] 2015-08-06 10:49
https://bugzilla.gnome.org/show_bug.cgi?id=727622

**Comment by gnumdk** [comment] 2015-08-06 10:49
Not sure what is happening, testing...

**Comment by gnumdk** [comment] 2015-08-06 10:53
Is lollypop playing while in background?

**Comment by hotoiledgoblinsack** [comment] 2015-08-06 15:04
A song is 'playing' (i.e. there is a song currently 'set' or 'active') but it's in the 'paused' state, so no sound is being played. Not sure if it makes a difference, but it may be useful to know that I have stop after current enabled as usual.

**Comment by gnumdk** [comment] 2015-08-10 19:52
Can't reproduce here, even leaving lollypop sleep a week... Stable GTK?

**Comment by hotoiledgoblinsack** [comment] 2015-08-11 15:55
Yes, GTK 3.16.6 on Arch x86-64. Strangely enough I noticed that I also can't always reproduce it after a couple of hours. It recently happened after half an hour of keeping it in the background.

Perhaps we should just pin it on my system being borked somehow, since it's not really a grave issue, it's not reliably reproducible and I have no idea how to further debug it if it happens again :P.

**Comment by gnumdk** [comment] 2015-08-12 14:43
I close it, reopen if you find more informations about this...

**Closed by gnumdk** 2015-08-12 14:43 UTC
