### ISSUE TITLE
Redshift conflict

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#773] opened 2016-10-06 18:03 UTC
## Env
- Lollypop version: 0.9.206
- [Redshift package](https://apps.fedoraproject.org/packages/redshift)
- Gtk Version: 3.20
- Linux distribution: Fedora 24

## Bug
I am using [Redshift](https://linuxfr.org/nodes/108684/comments/1675515) and when I click on play a music on first time, the screen which was red become white then come back red.

**Comment by gnumdk** [comment] 2016-10-06 19:30
Redshift bug... Lollypop disable suspend on playback...

**Comment by gnumdk** [comment] 2016-10-08 10:51
Closing this bug:
Installed redshift and can't reproduce issue... So I guess some other program is doing bad things on your computer....

**Closed by gnumdk** 2016-10-08 10:51 UTC
